jirapostgres:
  image: postgres:9.4
  expose:
   - "5432"
  volumes_from:
   - jiradatavolume
jiradatavolume:
  image: postgres:9.4
  volumes:
    - /var/lib/postgresql/data
jira:
  build: jira/
  ports: 
    - "8080:8080"
  links:
   - jirapostgres

stashpostgres:
  image: postgres:9.4
  expose:
   - "5432"
  volumes_from:
   - stashdatavolume
stashdatavolume:
  image: postgres:9.4
  volumes:
    - /var/lib/postgresql/data
stash:
  build: stash/
  ports: 
    - "7990:7990"
    - "7999:7999"
  links:
   - jira
   - stashpostgres
   - jirapostgres

confluencepostgres:
  image: postgres:9.4
  expose:
   - "5432"
  volumes_from:
   - confluencedatavolume
confluencedatavolume:
  image: postgres:9.4
  volumes:
    - /var/lib/postgresql/data
confluence:
  build: confluence/
  ports: 
    - "8090:8090"
  links:
   - jira
   - confluencepostgres
   - jirapostgres

bamboo:
  build: bamboo/
  ports: 
    - "8085:8085"
    - "54663:54663"
  links:
   - jira
   - jirapostgres